'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Heart, Minus, Plus, ShoppingBag } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useCart } from '@/lib/store';
import { ShopFooter, ShopHeader, ProductCard } from '@/components/ShopChrome';

export default function ProductView({ id }: { id?: string }) {
  const [product, setProduct] = useState<any>(null);
  const [similar, setSimilar] = useState<any[]>([]);
  const [qty, setQty] = useState(1);
  const [added, setAdded] = useState(false);
  const addItem = useCart((state) => state.addItem);
  useEffect(() => { const productId = id || window.location.pathname.split('/').pop(); if (!productId) return; supabase.from('products').select('*').eq('id', productId).single().then(async ({ data }) => { setProduct(data); if (data?.category) { const { data: more } = await supabase.from('products').select('*').eq('category', data.category).eq('is_active', true).neq('id', productId).limit(4); setSimilar(more || []); } }); }, [id]);
  if (!product) return <><ShopHeader/><div className="container-shop min-h-[60vh] grid place-items-center text-sm text-[var(--muted)]">Chargement de la pièce…</div><ShopFooter/></>;
  const gallery = [product.image_url, ...(product.gallery || [])].filter(Boolean);
  const price = product.discount_price || product.price;
  const add = () => { for (let i=0;i<qty;i++) addItem(product); setAdded(true); setTimeout(() => setAdded(false), 1800); };
  return <div><ShopHeader/><main className="container-shop py-8 md:py-12"><Link href="/" className="inline-flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.14em] text-[var(--muted)] hover:text-[var(--ink)]"><ArrowLeft size={14}/> Retour à la boutique</Link><div className="mt-8 grid gap-10 md:grid-cols-[1.05fr_.95fr] md:gap-16"><div className="grid grid-cols-2 gap-3">{gallery.map((image: string, i: number) => <div key={image+i} className={`product-image ${i===0?'col-span-2 aspect-[1.15]':'aspect-square'}`}><img src={image} alt={product.name}/></div>)}</div><div className="md:pt-8"><p className="eyebrow">{product.category || 'Collection Emmaashop'}</p><h1 className="display mt-4 text-5xl leading-none md:text-6xl">{product.name}</h1><div className="mt-6 flex items-center gap-3 text-xl"><strong>{price} €</strong>{product.discount_price && <span className="text-sm text-[var(--muted)] line-through">{product.price} €</span>}</div><p className="mt-8 border-y border-[var(--line)] py-7 text-sm leading-7 text-[var(--muted)]">{product.description || 'Une pièce choisie pour son caractère, sa coupe et la sensation qu’elle laisse.'}</p><div className="mt-7 flex items-center justify-between text-sm"><span className="font-bold">{product.stock > 0 ? `${product.stock} pièces disponibles` : 'Rupture de stock'}</span><Heart size={20} className="text-[var(--muted)]"/></div>{product.stock > 0 && <><div className="mt-7 flex items-center justify-between border border-[var(--line)] p-2"><span className="px-3 text-[11px] font-bold uppercase tracking-widest">Quantité</span><div className="flex items-center gap-5"><button onClick={() => setQty(Math.max(1,qty-1))} aria-label="Diminuer"><Minus size={16}/></button><span className="w-4 text-center font-bold">{qty}</span><button onClick={() => setQty(Math.min(product.stock,qty+1))} aria-label="Augmenter"><Plus size={16}/></button></div></div><button onClick={add} className="btn-primary mt-4 w-full">{added ? 'Ajouté au panier' : 'Ajouter au panier'} <ShoppingBag size={17}/></button></>}<div className="mt-8 grid gap-3 text-xs text-[var(--muted)]"><p><strong className="text-[var(--ink)]">Livraison.</strong> Expédition soignée dans toute la Côte d’Ivoire.</p><p><strong className="text-[var(--ink)]">Paiement.</strong> À la livraison, en toute simplicité.</p></div></div></div>{similar.length>0 && <section className="border-t border-[var(--line)] mt-24 pt-14"><div className="flex items-end justify-between"><div><p className="eyebrow">Vous aimerez aussi</p><h2 className="display mt-3 text-4xl">Dans la même histoire</h2></div><Link href="/#nouveautes" className="hidden text-xs font-bold uppercase tracking-widest sm:block">Tout voir <ArrowRight size={14} className="inline ml-1"/></Link></div><div className="mt-9 grid grid-cols-2 gap-4 md:grid-cols-4 md:gap-6">{similar.map((p) => <ProductCard key={p.id} product={p}/>)}</div></section>}</main><ShopFooter/></div>;
}
