'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Loader2, Search, Heart } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { ProductCard, ShopFooter, ShopHeader } from '@/components/ShopChrome';

export default function Home() {
  const [products, setProducts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('Tout');
  useEffect(() => { supabase.from('products').select('*').eq('is_active', true).order('created_at', { ascending: false }).then(({ data }) => { setProducts(data || []); setLoading(false); }); }, []);
  const categories = useMemo(() => ['Tout', ...Array.from(new Set(products.map((p) => p.category).filter(Boolean)))], [products]);
  const filtered = products.filter((p) => (category === 'Tout' || p.category === category) && `${p.name} ${p.description || ''}`.toLowerCase().includes(query.toLowerCase()));
  return <div><ShopHeader/><main>
    <section className="container-shop pt-7 md:pt-10"><div className="relative min-h-[560px] overflow-hidden rounded-[4px] bg-[#d9d3c6]"><img src="/tante-avec-fond.jpg" alt="Collection Emmaashop" className="absolute inset-0 h-full w-full object-cover object-[58%_30%]"/><div className="absolute inset-0 bg-gradient-to-r from-black/60 via-black/15 to-transparent"/><div className="relative flex min-h-[560px] max-w-xl flex-col justify-end p-7 pb-10 text-white md:p-14 md:pb-16"><p className="eyebrow !text-white/70 mb-5">Nouvelle collection · 2026</p><h1 className="display text-5xl leading-[.92] md:text-7xl">L’allure<br/><em>en héritage.</em></h1><p className="mt-6 max-w-sm text-sm leading-6 text-white/80">Des silhouettes pensées entre Abidjan, Paris et vos moments précieux.</p><a href="#nouveautes" className="btn-primary mt-8 w-fit !bg-white !text-[var(--ink)]">Découvrir la collection <ArrowRight size={16}/></a></div><div className="absolute right-5 top-5 hidden rounded-full border border-white/30 px-4 py-2 text-[10px] font-bold uppercase tracking-[.15em] text-white md:block">Fait avec intention</div></div></section>
    <section className="container-shop grid gap-5 border-b border-[var(--line)] py-7 text-center sm:grid-cols-3 sm:text-left"><div><p className="font-bold text-sm">Livraison soignée</p><p className="mt-1 text-xs text-[var(--muted)]">Dans toute la Côte d’Ivoire</p></div><div><p className="font-bold text-sm">Paiement à la livraison</p><p className="mt-1 text-xs text-[var(--muted)]">Simple, sûr, sans surprise</p></div><div><p className="font-bold text-sm">Une maison indépendante</p><p className="mt-1 text-xs text-[var(--muted)]">Des pièces choisies avec cœur</p></div></section>
    <section id="nouveautes" className="container-shop scroll-mt-28 py-20 md:py-28"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><p className="eyebrow mb-4">À découvrir maintenant</p><h2 className="display text-4xl md:text-5xl">Les pièces du moment</h2></div><p className="max-w-xs text-sm leading-6 text-[var(--muted)]">Une sélection de vêtements qui accompagnent les jours ordinaires comme les grandes occasions.</p></div><div className="mt-10 flex flex-col gap-4 border-y border-[var(--line)] py-4 md:flex-row md:items-center md:justify-between"><div className="flex gap-5 overflow-x-auto">{categories.map((c) => <button key={c} onClick={() => setCategory(c)} className={`whitespace-nowrap text-[11px] font-bold uppercase tracking-[.12em] ${category === c ? 'border-b-2 border-[var(--ink)] pb-2' : 'text-[var(--muted)]'}`}>{c}</button>)}</div><label className="flex items-center gap-2 border-b border-[var(--line)] pb-2 text-sm md:w-48"><Search size={15} className="text-[var(--muted)]"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Rechercher" className="w-full bg-transparent outline-none placeholder:text-[var(--muted)]"/></label></div>{loading ? <div className="grid min-h-48 place-items-center"><Loader2 className="animate-spin text-[var(--olive)]"/></div> : filtered.length ? <div className="grid grid-cols-2 gap-x-4 gap-y-12 md:grid-cols-3 lg:grid-cols-4 md:gap-x-6">{filtered.map((p) => <ProductCard key={p.id} product={p}/>)}</div> : <div className="py-20 text-center text-sm text-[var(--muted)]">Aucune pièce ne correspond à votre recherche.</div>}</section>
    <section id="collections" className="container-shop grid gap-4 md:grid-cols-2"><a className="group relative min-h-[390px] overflow-hidden bg-[#cfc8ba]" href="#nouveautes"><img src="/tante-detouree.png" alt="Collection essentielle" className="absolute inset-0 h-full w-full object-contain object-right-bottom transition-transform duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-r from-[#5b594d]/80 to-transparent"/><div className="relative flex h-full flex-col justify-end p-8 text-white"><p className="eyebrow !text-white/70">La sélection</p><h3 className="display mt-2 text-4xl">Les essentiels</h3><span className="mt-5 text-xs font-bold uppercase tracking-widest">Explorer <ArrowRight size={14} className="ml-1 inline"/></span></div></a><a className="group relative min-h-[390px] overflow-hidden bg-[#d8c8bb]" href="#nouveautes"><img src="/matante.jpg" alt="Collection cérémonie" className="absolute inset-0 h-full w-full object-cover object-top mix-blend-multiply transition-transform duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/65 to-transparent"/><div className="relative flex h-full flex-col justify-end p-8 text-white"><p className="eyebrow !text-white/70">Pour les moments forts</p><h3 className="display mt-2 text-4xl">Cérémonies</h3><span className="mt-5 text-xs font-bold uppercase tracking-widest">Voir la collection <ArrowRight size={14} className="ml-1 inline"/></span></div></a></section>
    <section id="maison" className="container-shop grid gap-10 py-24 md:grid-cols-[.8fr_1.2fr] md:items-center md:py-32"><div><p className="eyebrow mb-5">Notre maison</p><h2 className="display text-5xl leading-[.95] md:text-6xl">S’habiller<br/><em>de sens.</em></h2></div><div className="max-w-xl"><p className="text-lg leading-8">Emmaashop célèbre une mode africaine libre, généreuse et profondément personnelle. Chaque pièce est choisie pour sa coupe, son caractère et la sensation qu’elle laisse.</p><div className="mt-8 flex items-center gap-2 text-sm font-bold">En savoir plus <ArrowRight size={16}/></div></div></section>
  </main><ShopFooter/></div>;
}
