'use client';
import Link from 'next/link';
import { BarChart3, LayoutDashboard, LogOut, Package, ShoppingBag, Store } from 'lucide-react';
import { usePathname, useRouter } from 'next/navigation';
import { supabase } from '@/lib/supabase';
import InstallAppButton from '@/components/InstallAppButton';

export default function AdminChrome({ children, title, eyebrow }: { children: React.ReactNode; title: string; eyebrow: string }) {
  const pathname = usePathname(); const router = useRouter();
  const links = [{ href:'/admin', label:'Vue d’ensemble', icon:LayoutDashboard }, { href:'/admin/products', label:'Produits', icon:Package }, { href:'/admin/orders', label:'Commandes', icon:ShoppingBag }, { href:'/admin/analytics', label:'Statistiques', icon:BarChart3 }];
  const logout = async () => { await supabase.auth.signOut(); router.replace('/login'); };
  return <div className="min-h-screen overflow-x-hidden bg-[var(--paper)] text-[var(--ink)]"><header className="sticky top-0 z-40 border-b border-[var(--line)] bg-white/95 backdrop-blur"><div className="container-shop flex min-h-[64px] items-center justify-between gap-3 py-3 sm:h-[74px] sm:py-0"><Link href="/admin" className="display min-w-0 truncate text-xl font-semibold tracking-[-.06em] sm:text-2xl">Emmaashop<span className="text-[var(--olive)]">.</span><span className="ml-2 hidden font-sans text-[9px] font-bold uppercase tracking-[.18em] text-[var(--muted)] sm:inline">Studio</span></Link><div className="flex shrink-0 items-center gap-2 sm:gap-3"><InstallAppButton/><Link href="/" aria-label="Voir la boutique" className="hidden items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em] text-[var(--muted)] hover:text-[var(--ink)] sm:flex"><Store size={15}/> Voir la boutique</Link><button onClick={logout} aria-label="Se déconnecter" className="grid h-10 w-10 place-items-center text-[var(--muted)] hover:text-[var(--ink)] sm:flex sm:h-auto sm:w-auto sm:items-center sm:gap-2 sm:text-[10px] sm:font-bold sm:uppercase sm:tracking-[.14em]"><LogOut size={17}/><span className="hidden sm:inline">Sortir</span></button></div></div></header><div className="container-shop grid gap-6 py-6 sm:gap-10 sm:py-8 lg:grid-cols-[190px_1fr] lg:py-12"><aside className="lg:sticky lg:top-28 lg:h-fit"><p className="eyebrow mb-3 hidden lg:block">Navigation</p><nav className="grid grid-cols-3 gap-1 rounded-lg bg-white p-1 shadow-sm lg:grid-cols-1 lg:gap-1 lg:rounded-none lg:bg-transparent lg:p-0 lg:shadow-none">{links.map(({href,label,icon:Icon})=><Link key={href} href={href} className={`flex min-w-0 flex-col items-center justify-center gap-1 px-1 py-2.5 text-center text-[10px] font-bold leading-tight transition sm:text-xs lg:flex-row lg:justify-start lg:gap-3 lg:px-3 lg:py-3 lg:text-left ${pathname===href?'bg-[var(--ink)] text-white':'text-[var(--muted)] hover:bg-white hover:text-[var(--ink)]'}`}><Icon size={16}/><span className="truncate">{label}</span></Link>)}</nav></aside><main className="min-w-0"><div className="flex flex-col justify-between gap-4 border-b border-[var(--line)] pb-5 sm:flex-row sm:items-end sm:pb-7"><div><p className="eyebrow">{eyebrow}</p><h1 className="display mt-2 text-4xl leading-none sm:text-5xl">{title}</h1></div></div>{children}</main></div></div>;
}
